### ISSUE TITLE
 Input string was not in a correct format

### ISSUE THREAD

**Issue by Gremoire** [TypecastException/AspNet-Identity-2-With-Integer-Keys#2]
Hi John,

Received the following error in IdentitySample.Startup.ConfigureAuth at the app.UseCookieAuthentication call on line 25.

It is on a brand new build, no database setup yet.

{System.FormatException: Input string was not in a correct format
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at IdentitySample.Startup.<ConfigureAuth>b__3(ClaimsIdentity claim) in c:\Users\Riaan\Documents\Visual Studio 2013\Samples\AspNetIdentity2IntegerKeys\IdentitySample\App_Start\Startup.Auth.cs:line 37
   at Microsoft.AspNet.Identity.Owin.SecurityStampValidator.<>c__DisplayClass2`3.<<OnValidateIdentity>b__1>d__4.MoveNext()}

Web output:

Line 35:                         regenerateIdentityCallback: (manager, user) => user.GenerateUserIdentityAsync(manager),
Line 36:                         // Need to add THIS line because we added the third type argument (int) above:
Line 37:                             getUserIdCallback: (claim) => int.Parse(claim.GetUserId()))
Line 38:                 }
Line 39:             });

Any suggestions?

**Comment by xivSolutions** [comment]
Hmmmm...I seem to recall running into this when for whatever reason the user id being parsed was either null, or of some unsuitable string type. It's possible I missed something when I pushed this code up. Did you clone + build, or did you follow along with the article and build out your own?

**Comment by xivSolutions** [comment]
Were you trying to Register a new user, or log in with the default admin user?

**Comment by Gremoire** [comment]
Hi John,

I've used Git's "Download Zip" option to obtain the source code. Extracted the code, compiled and ran the application, which resulted in the exception stated above.

This happens upon first launch of the site, not even trying to login yet.

# 

Server Error in '/' Application.

Input string was not in a correct format.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.FormatException: Input string was not in a correct format.

Source Error: 

Line 35:                         regenerateIdentityCallback: (manager, user) => user.GenerateUserIdentityAsync(manager),
Line 36:                         // Need to add THIS line because we added the third type argument (int) above:
Line 37:                             getUserIdCallback: (claim) => int.Parse(claim.GetUserId()))
Line 38:                 }
Line 39:             });

# Source File: c:\Users\username\Documents\Visual Studio 2013\Samples\AspNetIdentity2IntegerKeys\IdentitySample\App_Start\Startup.Auth.cs    Line: 37

**Comment by xivSolutions** [comment]
That's really weird, especially considering this method isn't (shouldn't) even be called until you attempt to log in for the first time. 

Look in your user/documents folder, and see if there is a new or existing database there named IdentitySample-2-1-alpha1 or DefaultConnection or anything. If so, delete. Then, look in the IdentityConfig.cs file, and find find the `ApplicationDbInitializer : DropCreateDatabaseIfModelChanges<ApplicationDbContext>` and change to:

`ApplicationDbInitializer : DropCreateDatabaseAlways<ApplicationDbContext>`

Then re-build, re-run, and (Assuming you get as far as the app starting up), try logging in. 

On a final note, I have found that if there is a `.cshtml` file (in other words, a View) open as the active window in VS, when I run the project it seems to try to open the site to that URL. Close any View files which may be open. 

I gotta run off to work, but if you could update me on this, I will check in this evening. 

FWIW, I pulled down the .zip file, and ran it with no issues, though I had an existing database in my documents folder I needed to delete, since it was named the same from when I created the original project. 

There is enough "magic" happening behind the scenes with EF here that it can be confusing when stuff like this goes wrong.

**Comment by Gremoire** [comment]
Hi John,

I think I resolved the issue. As stated on your blog in the comments, I'm fairly new to ASP.NET development and MVC in particular.

Herewith what I think caused the issue (which might help someone else that runs into a similar situation):

I downloaded the "Strings" version of your template and tested that before I downloaded the "Integer" version. 

Even though I changed the database (Initial Catalogue) in the web.config for the Integer Template (so that I can compare the different database schemas between the 2 templates), I did not log out of the "String" template site. I just stopped the VS2013 debugger, and switched over to the "Integer" template source code, and ran the site again after changing the connection string and the website port.

I think the cookie stored in the browser from the "string" template was being picked up by the "Integer" template when it ran, thus causing the error.\

When I switched my browser from Chrome to IE, IE launched without any issues. I went on to clear the cookies from Chrome and launched the "Integer" site in Chrome again and it worked fine :)

Thanks for your assistance. It is greatly appreciated.

**Comment by fouimette** [comment]
I also ran across this issue and after reading @Gremoire last post I realized that I needed to delete any existing cookie(s) related to the site as they had a previous 'ClaimsIdentity' with a GUID as the UserId.

Hope that helps anyone else that stumbles across this issue.

**Comment by xivSolutions** [comment]
@fouimette @Gremoire - Both of you, thanks for taking the time to comment!

**Comment by Cloetn** [comment]
I had the same issue and it kept pursuing me while development. Either my cookie was getting invalid or the cookie changed for some magical reason and couldn't be parsed anymore. I couldn't even visit the logout page. I gave my own code a little edit:

```
getUserIdCallback: (id) => GrabUserId(id))

 public static int GrabUserId(System.Security.Claims.ClaimsIdentity claim)
    {
        int id;

        if (!int.TryParse(claim.GetUserId(), out id))
            return 0;
        else
            return id;
    }
```

When returning 0 it just logs you out because it couldn't recognize you as a user.

**Comment by rosdi** [comment]
I was following this guide. http://www.asp.net/identity/overview/extensibility/change-primary-key-for-users-in-aspnet-identity

Had the same issue, clearing the cookie as @Gremoire suggested solved it. Thanks!

**Comment by Praneshjs** [comment]
i faced same issue, i tried debugging with different browser then it worked! thanks for your help

**Comment by LidiaKovalchuk** [comment]
I had the same issue and clearing the cookie helped. @Gremoire, thank you!

**Comment by xivSolutions** [comment]
@all - Yeah, like with many web sites, your login info is stored in a cookie. If you log out, and attempt to log in as another user, you will need to either close the browser window, or clear the cookie. Or, of course, develop in an "incognito" window.

**Comment by tejaprakash** [comment]
I have faced same issue due to cookie. I cleared the cookies and its works like charm!!

**Comment by aronipurwanto** [comment]
I had same issue, but have been solved with @Cloetn solution.. thank @Cloetn
