### ISSUE TITLE
Use Guid Instead of Integer

### ISSUE THREAD

**Issue by clockwiseq** [TypecastException/AspNet-Identity-2-With-Integer-Keys#6]
First of all, thank you for your tutorial on your site and the example code.  I am a lover of extremely long identifiers and thought I would try my hand at using Guid as the type for the key (since you were able to use the extension method to use int, I thought it should be as simple as a find/replace, but it would seem it is not.  Have you tried this and if so, how were you able to get around the issue:

![image](https://cloud.githubusercontent.com/assets/6662538/6540029/760e06fe-c44e-11e4-8a8c-642bf0d665a5.png)

**Comment by xivSolutions** [comment]
The default ASP.NET Identity implementation uses a `string` type for the PK, but it is actauly a string representation of a GUID. I think if you want to use a GUID in the backing table, you  may still need to parse to string on the way into your application, and back to a GUID on the way into the database. 

Notice in the default implementation for ApplicationUser, for example, the Id property is set in the constructor (you can see this using Telerik JustDecompile)

`Id = Guid.NewGuid().ToString();`

So in reality you are halfway there. However, I recommend sticking with the string in the Db unless there is a compelling reason to do otherwise...

**Comment by clockwiseq** [comment]
Thanks for the response.  I guess I'll stick with the Guid string.
